"""Add missing columns to Heroku

Revision ID: 06756e52db35
Revises: 6d3c2bd01fda
Create Date: 2026-01-06 21:23:14.646254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06756e52db35'
down_revision: Union[str, None] = '6d3c2bd01fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    
    # Create ENUM types first
    participantstatus = postgresql.ENUM('PENDING', 'CONFIRMED', 'REJECTED', 'ACTIVE', 'ELIMINATED', name='participantstatus', create_type=False)
    participantstatus.create(op.get_bind(), checkfirst=True)
    
    brackettype = postgresql.ENUM('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', name='brackettype', create_type=False)
    brackettype.create(op.get_bind(), checkfirst=True)
    
    # Drop default before type conversion for status
    op.execute("ALTER TABLE tournament_registrations ALTER COLUMN status DROP DEFAULT")
    
    # Update lowercase values to uppercase to match ENUM
    op.execute("UPDATE tournament_registrations SET status = UPPER(status)")
    
    # Convert status column with USING clause
    op.execute("ALTER TABLE tournament_registrations ALTER COLUMN status TYPE participantstatus USING status::text::participantstatus")
    
    # Restore default with correct type
    op.execute("ALTER TABLE tournament_registrations ALTER COLUMN status SET DEFAULT 'PENDING'::participantstatus")
    
    # Convert bracket_type column with USING clause  
    op.execute("ALTER TABLE tournament_rules ALTER COLUMN bracket_type TYPE brackettype USING bracket_type::text::brackettype")
    
    op.create_index(op.f('ix_tournament_rules_id'), 'tournament_rules', ['id'], unique=False)
    op.create_unique_constraint(None, 'tournament_rules', ['tournament_id'])
    op.alter_column('tournaments', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('tournaments', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'end_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tournaments', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'tournament_rules', type_='unique')
    op.drop_index(op.f('ix_tournament_rules_id'), table_name='tournament_rules')
    op.alter_column('tournament_rules', 'bracket_type',
               existing_type=sa.Enum('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', name='brackettype'),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
    op.alter_column('tournament_registrations', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'ACTIVE', 'ELIMINATED', name='participantstatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_players_id'), table_name='players')
    # ### end Alembic commands ###
