"""Add tables table and update matches for PHASE 3

Revision ID: 82ac04ee3193
Revises: 9a538e7d9564
Create Date: 2026-01-09 15:41:29.228577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ac04ee3193'
down_revision: Union[str, None] = '9a538e7d9564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('video_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'matches', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'video_url')
    op.drop_column('matches', 'table_id')
    # ### end Alembic commands ###
