"""add_tables_for_tournament

Revision ID: eccb6a5912b1
Revises: 20260113_remove_enums
Create Date: 2026-01-13 19:41:21.073895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccb6a5912b1'
down_revision: Union[str, None] = '20260113_remove_enums'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_matches_next_match_loser_id', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'matches', ['next_match_loser_id'], ['id'])
    op.add_column('tables', sa.Column('tournament_id', sa.Integer(), nullable=False))
    op.add_column('tables', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('tables', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('tables', sa.Column('is_occupied', sa.Boolean(), nullable=False))
    op.add_column('tables', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tables', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tables_id'), 'tables', ['id'], unique=False)
    op.create_foreign_key(None, 'tables', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tables', 'description')
    op.drop_column('tables', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tables', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_index(op.f('ix_tables_id'), table_name='tables')
    op.drop_column('tables', 'updated_at')
    op.drop_column('tables', 'created_at')
    op.drop_column('tables', 'is_occupied')
    op.drop_column('tables', 'is_active')
    op.drop_column('tables', 'name')
    op.drop_column('tables', 'tournament_id')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('fk_matches_next_match_loser_id', 'matches', 'matches', ['next_match_loser_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
